### ISSUE TITLE
If I submit a blank form on the signin, I get a spinner that goes forever

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/WaterReporter-iOS#37]
See screenshot
![img_2317](https://cloud.githubusercontent.com/assets/3653904/9553823/a4c1152a-4d8f-11e5-8a1e-f8899eb12a3e.PNG)

**Comment by joshuapowell** [comment]
![screen shot 2015-09-01 at 9 24 26 am](https://cloud.githubusercontent.com/assets/569351/9605360/430ceb16-508b-11e5-9686-693ebaaef060.png)
